Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100

AllCops:
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - bin/*
    - node_modules/**/*

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
    - config/environments/production.rb
    - Guardfile
    - config/initializers/simple_form_bootstrap.rb
    - config/routes.rb
    - lib/tasks/*
    - app/admin/*
    - app/models/order.rb

Metrics/ClassLength:
  Exclude:
    - app/models/order.rb
    - app/models/line_item.rb

Lint/UselessAssignment:
  Exclude:
    - app/models/category.rb

Layout/AlignHash:
  Enabled: False

Style/AsciiComments:
  Enabled: False

Style/DoubleNegation:
  Enabled: False

Rails/OutputSafety:
  Exclude:
    - app/helpers/internationalization_helper.rb
    - config/environment.rb

GlobalVars:
  AllowedVariables:
    - $redis

Rails/Output:
  Exclude:
    - db/seeds.rb

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging
