Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100

AllCops:
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - bin/*
    - node_modules/**/*

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
    - Guardfile
    - config/initializers/simple_form_bootstrap.rb
    - lib/tasks/*
    - app/admin/*

Lint/UselessAssignment:
  Exclude:
    - app/models/category.rb

Layout/AlignHash:
  Enabled: False

Style/AsciiComments:
  Enabled: False

Rails/OutputSafety:
  Exclude:
    - app/helpers/internationalization_helper.rb

GlobalVars:
  AllowedVariables:
    - $redis

Rails/Output:
  Exclude:
    - db/seeds.rb
