require: rubocop-rails

Rails:
  Enabled: true


AllCops:
  Exclude:
    - db/migrate/*
    - db/schema.rb
    - bin/*
    - node_modules/**/*

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

# todo
Rails/HelperInstanceVariable:
  Exclude:
    - app/helpers/application_helper.rb

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
    - config/environments/production.rb
    - Guardfile
    - config/initializers/simple_form_bootstrap.rb
    - config/routes.rb
    - lib/tasks/*
    - app/admin/*
    - app/models/order.rb
    - spec/features/*.rb
    - spec/models/*.rb

Metrics/MethodLength:
  Exclude:
    - app/models/sitemaps/sitemap.rb

Metrics/AbcSize:
  Exclude:
    - app/models/sitemaps/sitemap.rb
    - app/helpers/application_helper.rb

Metrics/ClassLength:
  Exclude:
    - app/models/order.rb
    - app/models/line_item.rb

Lint/UselessAssignment:
  Exclude:
    - app/models/category.rb

Lint/SuppressedException:
  Enabled: False

Layout/HashAlignment:
  Enabled: False

Metrics/LineLength:
  Max: 100
  Exclude:
    - config/routes.rb
    - spec/models/*.rb

Naming/MemoizedInstanceVariableName:
  Enabled: False

Style/AsciiComments:
  Enabled: False

Style/DoubleNegation:
  Enabled: False

Style/AndOr:
  Exclude:
    - app/controllers/clients_controller.rb

Rails/OutputSafety:
  Exclude:
    - app/helpers/internationalization_helper.rb
    - config/environment.rb

GlobalVars:
  AllowedVariables:
    - $redis

Rails/Output:
  Exclude:
    - db/seeds.rb

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging

Style/FormatStringToken:
  Enabled: False

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
